- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: starry-core-311909
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/florian/git/verkstedt-coding-challange/service_account_credentials.json
      zone: "europe-north1-a"
      region: "europe-north1"
  roles:
    - google_setup

      #- name: Manage web instances
      #  hosts: web
      #  become: True
      #  roles:
      #    - web
